export const LOAD_LOGIN = 'LOAD_LOGIN';
export const LOAD_LOGIN_SUCCESS = 'LOAD_LOGIN_SUCCESS';
export const LOAD_LOGIN_FAILURE = 'LOAD_LOGIN_FAILURE';

export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';

export const LOAD_REGISTER = 'LOAD_REGISTER';
export const LOAD_REGISTER_SUCCESS = 'LOAD_REGISTER_SUCCESS';
export const LOAD_REGISTER_FAILURE = 'LOAD_REGISTER_FAILURE';

export const POST_REGISTER = 'POST_REGISTER';
export const POST_REGISTER_SUCCESS = 'POST_REGISTER_SUCCESS';
export const POST_REGISTER_FAILURE = 'POST_REGISTER_FAILURE';
